# Generated by Django 3.0 on 2019-12-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191211_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
